### ISSUE TITLE
Error in typings

### ISSUE THREAD

**Issue by erickskrauch** [voximplant/voxengine-ci#2]
Please review the typings before releasing a new version. And maybe introduce some changelogs, since this project is used by others 🤞
![image](https://github.com/voximplant/voxengine-ci/assets/4787256/17c430a2-5207-4009-9fbc-87a1a142e40f)

**Comment by NikolasMelui** [comment]
Hi, @erickskrauch!
Thanks for the report, this is really a bug, we will fix it in the next release. For now you can use the "@ts-ignore" to prevent the compiler error.

**Comment by NikolasMelui** [comment]
Regarding changelogs, we are working on this, but this is a non-trivial task, so you shouldn’t expect them to appear in the near future.

**Comment by NikolasMelui** [comment]
Done, try the **7.0.0** version - https://www.npmjs.com/package/@voximplant/voxengine-ci/v/7.0.0
